### ISSUE TITLE
Wish: Linked at https://github.com/espressif

### ISSUE THREAD

**Issue by stappersg** [esp-rs/.github#1]
FWIW I think it would be a good thing if https://github.com/espressif has a link to https://github.com/esp-rs

**Comment by jessebraham** [comment]
@pedrominatel would we be able to add this?

**Comment by pedrominatel** [comment]
Hi, @stappersg

We will include the [esp-rs](https://github.com/esp-rs) link on the Espressif projects list [here](https://github.com/esp-rs).

Thanks!

**Comment by pedrominatel** [comment]
PR created: https://github.com/espressif/.github/pull/1

**Comment by pedrominatel** [comment]
Done!

https://github.com/espressif/.github/blob/main/profile/esp-projects.md#related-and-third-party-projects

**Comment by jessebraham** [comment]
Thanks for doing that Pedro!
